# Generated by Django 3.0.3 on 2020-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20200229_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
